### PR TITLE
Adds Beez to the workers list

### PR DESCRIPTION
**Pull request by gottfrois**

### CODE REVIEW

**Comment by saig0** [comment]
Hi @gottfrois :wave: 

Your project [Beez](https://github.com/gottfrois/beez) sounds interesting :bee: I guess that it would fit in the "clients" sections as far as I understand.

Why did you close the RP?

**Comment by saig0** [comment]
The CLA is just about the contribution to this repository itself (i.e. modifying the README) and does not include the code of your project. 

If you're still curious about it but want to add your project to the list then I can also add your project to the README :)

**Comment by gottfrois** [comment]
I'll submit the PR again then, thanks for the explanation 🐝

**Comment by gottfrois** [comment]
BTW the gem qualify as a worker really since it polls jobs and executes them in the context of a ruby/rails app 👍

**Comment by gottfrois** [comment]
@saig0 here it is https://github.com/zeebe-io/awesome-zeebe/pull/17

**Pull request closed without merging**
